{
'name': "Hostel Management",
'summary': "Manage Hostel easily",
'description': "Efficiently manage the entire residential facility in the school.",
'author': "Julien",
'website': "http://www.example.com",
'category': 'Hostel',
'version': '17.0.6.0.3',
'depends': ['base', 'mail', 'web_cohort', 'web_gantt', 'web_map', 'base_setup', 'website', 'utm'],
'assets': {
    'web.assets_frontend': [
        'my_hostel/static/src/scss/hostel.scss',
        'my_hostel/static/src/js/hostel.js',
        'my_hostel/static/src/js/snippets.js',
    ],
    'web.assets_backend': [
        # scss
        'my_hostel/static/src/scss/field_widget.scss',
        'my_hostel/static/src/scss/color_widget.scss',
        
        # js
        'my_hostel/static/src/js/field_widget.js',
        'my_hostel/static/src/js/color_widget.js',
        'my_hostel/static/src/js/m2m_group_arch_parser.js',
        'my_hostel/static/src/js/m2m_group_view.js',
        'my_hostel/static/src/js/m2m_group_renderer.js',
        'my_hostel/static/src/js/m2m_group_model.js',
        'my_hostel/static/src/js/m2m_group_controller.js',
        'my_hostel/static/src/js/my_hostel_tour.js',
        'my_hostel/static/src/js/my_hostel_test_tour.js',
        'my_hostel/static/src/js/component.js',
        
        # xml
        'my_hostel/static/src/xml/field_widget.xml',
        'my_hostel/static/src/xml/color_widget.xml',
        'my_hostel/static/src/xml/m2m_group_controller.xml',
        'my_hostel/static/src/xml/m2m_group_renderer.xml',
        'my_hostel/static/src/xml/m2m_group_view.xml',
    ],
    'web.qunit_suite_tests': [
        'my_hostel/static/tests/**/*',
    ],
},
'data': [
    "security/hostel_security.xml",
    "security/ir.model.access.csv",
    "security/rules.xml",
    "security/security_rules.xml",
    "views/hostel.xml",
    "views/hostel_categ.xml",
    "views/hostel_room.xml",
    "wizards/assign_room_student_wizard.xml",
    "views/hostel_student.xml",
    "views/hostel_amenities.xml",
    "views/hostel_book.xml",
    "views/hostel_room_availability.xml",
    "views/res_config_settings.xml",
    "views/templates.xml",
    "views/hostel_templates.xml",
    "views/snippets.xml",
    "views/inquiries_view.xml",
    "views/form_template.xml",
    "data/data.xml",
    "data/data_noupdate.xml",
    "data/room_stages.xml",
    "reports/hostel_room_detail_report.xml",
    "reports/hostel_room_detail_report_template.xml"
],
'pre_init_hook': 'pre_init_hook_hostel',
'post_init_hook': 'add_room_hook',
'uninstall_hook': 'uninstall_hook_user',
'demo': [
    'demo/demo.xml',
],
}