{
'name': "Hostel Management",
'summary': "Manage Hostel easily",
'description': "Efficiently manage the entire residential facility in the school.",
'author': "Julien",
'website': "http://www.example.com",
'category': 'Hostel',
'version': '17.0.6.0.3',
'depends': ['base', 'mail', 'web_cohort', 'web_gantt', 'web_map', 'base_setup'],
'data': [
    "security/security_rules.xml",
    "security/hostel_security.xml",
    "security/ir.model.access.csv",
    "views/hostel.xml",
    "views/hostel_categ.xml",
    "views/hostel_room.xml",
    "wizards/assign_room_student_wizard.xml",
    "views/hostel_student.xml",
    "views/hostel_amenities.xml",
    "views/hostel_book.xml",
    "views/hostel_room_availability.xml",
    "views/res_config_settings.xml",
    "data/data.xml",
    "data/data_noupdate.xml",
    "data/room_stages.xml",
    "reports/hostel_room_detail_report.xml",
    "reports/hostel_room_detail_report_template.xml"
],
'pre_init_hook': 'pre_init_hook_hostel',
'post_init_hook': 'add_room_hook',
'uninstall_hook': 'uninstall_hook_user',
'demo': [
    'demo/demo.xml',
],
}