from . import hostel
from . import base_archive
from . import hostel_room
from . import hostel_room_copy
from . import hostel_student
from . import hostel_amenities
from . import hostel_categ
from . import hostel_book
from . import hostel_room_availability
from . import hostel_room_stage
from . import res_config_settings
from . import ir_http
from . import inquiries
from . import base
from . import ir_action_act_window
from . import ir_ui_view